// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hsftxglfgqokakfgxgvd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhzZnR4Z2xmZ3Fva2FrZmd4Z3ZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxOTY1NTAsImV4cCI6MjA2MTc3MjU1MH0.CIckT_hUv2bhUR4qMbq5cBvHx-_Z7sI4V08_LrU9FxY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);